// Code generated by Prisma (prisma@1.29.1). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from 'graphql'
import {
  BaseClientOptions,
  makePrismaClientClass,
  Model
} from 'prisma-client-lib'
import { typeDefs } from './prisma-schema'

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U]

export interface Exists {
  category: (where?: CategoryWhereInput) => Promise<boolean>
  comment: (where?: CommentWhereInput) => Promise<boolean>
  link: (where?: LinkWhereInput) => Promise<boolean>
  review: (where?: ReviewWhereInput) => Promise<boolean>
  service: (where?: ServiceWhereInput) => Promise<boolean>
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>
}

export interface Prisma {
  $exists: Exists
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>

  /**
   * Queries
   */

  category: (where: CategoryWhereUniqueInput) => CategoryPromise
  categories: (args?: {
    where?: CategoryWhereInput
    orderBy?: CategoryOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Category>
  categoriesConnection: (args?: {
    where?: CategoryWhereInput
    orderBy?: CategoryOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => CategoryConnectionPromise
  comment: (where: CommentWhereUniqueInput) => CommentPromise
  comments: (args?: {
    where?: CommentWhereInput
    orderBy?: CommentOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Comment>
  commentsConnection: (args?: {
    where?: CommentWhereInput
    orderBy?: CommentOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => CommentConnectionPromise
  link: (where: LinkWhereUniqueInput) => LinkPromise
  links: (args?: {
    where?: LinkWhereInput
    orderBy?: LinkOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Link>
  linksConnection: (args?: {
    where?: LinkWhereInput
    orderBy?: LinkOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => LinkConnectionPromise
  review: (where: ReviewWhereUniqueInput) => ReviewPromise
  reviews: (args?: {
    where?: ReviewWhereInput
    orderBy?: ReviewOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Review>
  reviewsConnection: (args?: {
    where?: ReviewWhereInput
    orderBy?: ReviewOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => ReviewConnectionPromise
  service: (where: ServiceWhereUniqueInput) => ServicePromise
  services: (args?: {
    where?: ServiceWhereInput
    orderBy?: ServiceOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => FragmentableArray<Service>
  servicesConnection: (args?: {
    where?: ServiceWhereInput
    orderBy?: ServiceOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => ServiceConnectionPromise
  node: (args: { id: ID_Output }) => Node

  /**
   * Mutations
   */

  createCategory: (data: CategoryCreateInput) => CategoryPromise
  updateCategory: (args: {
    data: CategoryUpdateInput
    where: CategoryWhereUniqueInput
  }) => CategoryPromise
  updateManyCategories: (args: {
    data: CategoryUpdateManyMutationInput
    where?: CategoryWhereInput
  }) => BatchPayloadPromise
  upsertCategory: (args: {
    where: CategoryWhereUniqueInput
    create: CategoryCreateInput
    update: CategoryUpdateInput
  }) => CategoryPromise
  deleteCategory: (where: CategoryWhereUniqueInput) => CategoryPromise
  deleteManyCategories: (where?: CategoryWhereInput) => BatchPayloadPromise
  createComment: (data: CommentCreateInput) => CommentPromise
  updateComment: (args: {
    data: CommentUpdateInput
    where: CommentWhereUniqueInput
  }) => CommentPromise
  updateManyComments: (args: {
    data: CommentUpdateManyMutationInput
    where?: CommentWhereInput
  }) => BatchPayloadPromise
  upsertComment: (args: {
    where: CommentWhereUniqueInput
    create: CommentCreateInput
    update: CommentUpdateInput
  }) => CommentPromise
  deleteComment: (where: CommentWhereUniqueInput) => CommentPromise
  deleteManyComments: (where?: CommentWhereInput) => BatchPayloadPromise
  createLink: (data: LinkCreateInput) => LinkPromise
  updateLink: (args: {
    data: LinkUpdateInput
    where: LinkWhereUniqueInput
  }) => LinkPromise
  updateManyLinks: (args: {
    data: LinkUpdateManyMutationInput
    where?: LinkWhereInput
  }) => BatchPayloadPromise
  upsertLink: (args: {
    where: LinkWhereUniqueInput
    create: LinkCreateInput
    update: LinkUpdateInput
  }) => LinkPromise
  deleteLink: (where: LinkWhereUniqueInput) => LinkPromise
  deleteManyLinks: (where?: LinkWhereInput) => BatchPayloadPromise
  createReview: (data: ReviewCreateInput) => ReviewPromise
  updateReview: (args: {
    data: ReviewUpdateInput
    where: ReviewWhereUniqueInput
  }) => ReviewPromise
  updateManyReviews: (args: {
    data: ReviewUpdateManyMutationInput
    where?: ReviewWhereInput
  }) => BatchPayloadPromise
  upsertReview: (args: {
    where: ReviewWhereUniqueInput
    create: ReviewCreateInput
    update: ReviewUpdateInput
  }) => ReviewPromise
  deleteReview: (where: ReviewWhereUniqueInput) => ReviewPromise
  deleteManyReviews: (where?: ReviewWhereInput) => BatchPayloadPromise
  createService: (data: ServiceCreateInput) => ServicePromise
  updateService: (args: {
    data: ServiceUpdateInput
    where: ServiceWhereUniqueInput
  }) => ServicePromise
  updateManyServices: (args: {
    data: ServiceUpdateManyMutationInput
    where?: ServiceWhereInput
  }) => BatchPayloadPromise
  upsertService: (args: {
    where: ServiceWhereUniqueInput
    create: ServiceCreateInput
    update: ServiceUpdateInput
  }) => ServicePromise
  deleteService: (where: ServiceWhereUniqueInput) => ServicePromise
  deleteManyServices: (where?: ServiceWhereInput) => BatchPayloadPromise

  /**
   * Subscriptions
   */

  $subscribe: Subscription
}

export interface Subscription {
  category: (
    where?: CategorySubscriptionWhereInput
  ) => CategorySubscriptionPayloadSubscription
  comment: (
    where?: CommentSubscriptionWhereInput
  ) => CommentSubscriptionPayloadSubscription
  link: (
    where?: LinkSubscriptionWhereInput
  ) => LinkSubscriptionPayloadSubscription
  review: (
    where?: ReviewSubscriptionWhereInput
  ) => ReviewSubscriptionPayloadSubscription
  service: (
    where?: ServiceSubscriptionWhereInput
  ) => ServiceSubscriptionPayloadSubscription
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T
}

/**
 * Types
 */

export type ServiceOrderByInput =
  | 'address_ASC'
  | 'address_DESC'
  | 'createdAt_ASC'
  | 'createdAt_DESC'
  | 'description_ASC'
  | 'description_DESC'
  | 'freetrial_ASC'
  | 'freetrial_DESC'
  | 'id_ASC'
  | 'id_DESC'
  | 'isOnline_ASC'
  | 'isOnline_DESC'
  | 'inquiry_ASC'
  | 'inquiry_DESC'
  | 'likeCount_ASC'
  | 'likeCount_DESC'
  | 'multiplans_ASC'
  | 'multiplans_DESC'
  | 'note_ASC'
  | 'note_DESC'
  | 'phonenumber_ASC'
  | 'phonenumber_DESC'
  | 'photoURL_ASC'
  | 'photoURL_DESC'
  | 'place_ASC'
  | 'place_DESC'
  | 'price_ASC'
  | 'price_DESC'
  | 'rating_ASC'
  | 'rating_DESC'
  | 'ratingCount_ASC'
  | 'ratingCount_DESC'
  | 'tagline_ASC'
  | 'tagline_DESC'
  | 'title_ASC'
  | 'title_DESC'
  | 'updatedAt_ASC'
  | 'updatedAt_DESC'
  | 'url_ASC'
  | 'url_DESC'
  | 'viewCount_ASC'
  | 'viewCount_DESC'
  | 'yomigana_ASC'
  | 'yomigana_DESC'

export type ReviewOrderByInput =
  | 'id_ASC'
  | 'id_DESC'
  | 'createdAt_ASC'
  | 'createdAt_DESC'
  | 'updatedAt_ASC'
  | 'updatedAt_DESC'
  | 'rate_ASC'
  | 'rate_DESC'
  | 'rating_ASC'
  | 'rating_DESC'
  | 'text_ASC'
  | 'text_DESC'
  | 'serviceId_ASC'
  | 'serviceId_DESC'
  | 'ownerId_ASC'
  | 'ownerId_DESC'

export type CategoryOrderByInput =
  | 'id_ASC'
  | 'id_DESC'
  | 'createdAt_ASC'
  | 'createdAt_DESC'
  | 'updatedAt_ASC'
  | 'updatedAt_DESC'
  | 'name_ASC'
  | 'name_DESC'
  | 'shortDescription_ASC'
  | 'shortDescription_DESC'
  | 'description_ASC'
  | 'description_DESC'

export type CommentOrderByInput =
  | 'id_ASC'
  | 'id_DESC'
  | 'createdAt_ASC'
  | 'createdAt_DESC'
  | 'updatedAt_ASC'
  | 'updatedAt_DESC'
  | 'text_ASC'
  | 'text_DESC'
  | 'ownerId_ASC'
  | 'ownerId_DESC'

export type LinkOrderByInput =
  | 'id_ASC'
  | 'id_DESC'
  | 'author_ASC'
  | 'author_DESC'
  | 'content_ASC'
  | 'content_DESC'
  | 'description_ASC'
  | 'description_DESC'
  | 'publishedAt_ASC'
  | 'publishedAt_DESC'
  | 'sourceId_ASC'
  | 'sourceId_DESC'
  | 'sourceName_ASC'
  | 'sourceName_DESC'
  | 'title_ASC'
  | 'title_DESC'
  | 'url_ASC'
  | 'url_DESC'
  | 'createdAt_ASC'
  | 'createdAt_DESC'
  | 'updatedAt_ASC'
  | 'updatedAt_DESC'

export type MutationType = 'CREATED' | 'UPDATED' | 'DELETED'

export interface ReviewUpdateWithoutServiceDataInput {
  rate?: Int
  rating?: Int
  text?: String
  serviceId?: String
  ownerId?: String
}

export type CategoryWhereUniqueInput = AtLeastOne<{
  id: ID_Input
}>

export interface CategoryUpsertWithoutServicesInput {
  update: CategoryUpdateWithoutServicesDataInput
  create: CategoryCreateWithoutServicesInput
}

export interface CategoryCreateOneWithoutServicesInput {
  create?: CategoryCreateWithoutServicesInput
  connect?: CategoryWhereUniqueInput
}

export interface CategoryUpdateWithoutServicesDataInput {
  name?: String
  shortDescription?: String
  description?: String
}

export interface ReviewUpdateManyDataInput {
  rate?: Int
  rating?: Int
  text?: String
  serviceId?: String
  ownerId?: String
}

export interface CategoryUpdateOneWithoutServicesInput {
  create?: CategoryCreateWithoutServicesInput
  update?: CategoryUpdateWithoutServicesDataInput
  upsert?: CategoryUpsertWithoutServicesInput
  delete?: Boolean
  disconnect?: Boolean
  connect?: CategoryWhereUniqueInput
}

export interface ServiceSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType
  updatedFields_contains?: String
  updatedFields_contains_every?: String[] | String
  updatedFields_contains_some?: String[] | String
  node?: ServiceWhereInput
  AND?: ServiceSubscriptionWhereInput[] | ServiceSubscriptionWhereInput
  OR?: ServiceSubscriptionWhereInput[] | ServiceSubscriptionWhereInput
  NOT?: ServiceSubscriptionWhereInput[] | ServiceSubscriptionWhereInput
}

export interface CategoryWhereInput {
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  name?: String
  name_not?: String
  name_in?: String[] | String
  name_not_in?: String[] | String
  name_lt?: String
  name_lte?: String
  name_gt?: String
  name_gte?: String
  name_contains?: String
  name_not_contains?: String
  name_starts_with?: String
  name_not_starts_with?: String
  name_ends_with?: String
  name_not_ends_with?: String
  services_every?: ServiceWhereInput
  services_some?: ServiceWhereInput
  services_none?: ServiceWhereInput
  shortDescription?: String
  shortDescription_not?: String
  shortDescription_in?: String[] | String
  shortDescription_not_in?: String[] | String
  shortDescription_lt?: String
  shortDescription_lte?: String
  shortDescription_gt?: String
  shortDescription_gte?: String
  shortDescription_contains?: String
  shortDescription_not_contains?: String
  shortDescription_starts_with?: String
  shortDescription_not_starts_with?: String
  shortDescription_ends_with?: String
  shortDescription_not_ends_with?: String
  description?: String
  description_not?: String
  description_in?: String[] | String
  description_not_in?: String[] | String
  description_lt?: String
  description_lte?: String
  description_gt?: String
  description_gte?: String
  description_contains?: String
  description_not_contains?: String
  description_starts_with?: String
  description_not_starts_with?: String
  description_ends_with?: String
  description_not_ends_with?: String
  AND?: CategoryWhereInput[] | CategoryWhereInput
  OR?: CategoryWhereInput[] | CategoryWhereInput
  NOT?: CategoryWhereInput[] | CategoryWhereInput
}

export interface ServiceWhereInput {
  address?: String
  address_not?: String
  address_in?: String[] | String
  address_not_in?: String[] | String
  address_lt?: String
  address_lte?: String
  address_gt?: String
  address_gte?: String
  address_contains?: String
  address_not_contains?: String
  address_starts_with?: String
  address_not_starts_with?: String
  address_ends_with?: String
  address_not_ends_with?: String
  category?: CategoryWhereInput
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  description?: String
  description_not?: String
  description_in?: String[] | String
  description_not_in?: String[] | String
  description_lt?: String
  description_lte?: String
  description_gt?: String
  description_gte?: String
  description_contains?: String
  description_not_contains?: String
  description_starts_with?: String
  description_not_starts_with?: String
  description_ends_with?: String
  description_not_ends_with?: String
  freetrial?: String
  freetrial_not?: String
  freetrial_in?: String[] | String
  freetrial_not_in?: String[] | String
  freetrial_lt?: String
  freetrial_lte?: String
  freetrial_gt?: String
  freetrial_gte?: String
  freetrial_contains?: String
  freetrial_not_contains?: String
  freetrial_starts_with?: String
  freetrial_not_starts_with?: String
  freetrial_ends_with?: String
  freetrial_not_ends_with?: String
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  isOnline?: Boolean
  isOnline_not?: Boolean
  inquiry?: String
  inquiry_not?: String
  inquiry_in?: String[] | String
  inquiry_not_in?: String[] | String
  inquiry_lt?: String
  inquiry_lte?: String
  inquiry_gt?: String
  inquiry_gte?: String
  inquiry_contains?: String
  inquiry_not_contains?: String
  inquiry_starts_with?: String
  inquiry_not_starts_with?: String
  inquiry_ends_with?: String
  inquiry_not_ends_with?: String
  likeCount?: Int
  likeCount_not?: Int
  likeCount_in?: Int[] | Int
  likeCount_not_in?: Int[] | Int
  likeCount_lt?: Int
  likeCount_lte?: Int
  likeCount_gt?: Int
  likeCount_gte?: Int
  multiplans?: String
  multiplans_not?: String
  multiplans_in?: String[] | String
  multiplans_not_in?: String[] | String
  multiplans_lt?: String
  multiplans_lte?: String
  multiplans_gt?: String
  multiplans_gte?: String
  multiplans_contains?: String
  multiplans_not_contains?: String
  multiplans_starts_with?: String
  multiplans_not_starts_with?: String
  multiplans_ends_with?: String
  multiplans_not_ends_with?: String
  note?: String
  note_not?: String
  note_in?: String[] | String
  note_not_in?: String[] | String
  note_lt?: String
  note_lte?: String
  note_gt?: String
  note_gte?: String
  note_contains?: String
  note_not_contains?: String
  note_starts_with?: String
  note_not_starts_with?: String
  note_ends_with?: String
  note_not_ends_with?: String
  phonenumber?: String
  phonenumber_not?: String
  phonenumber_in?: String[] | String
  phonenumber_not_in?: String[] | String
  phonenumber_lt?: String
  phonenumber_lte?: String
  phonenumber_gt?: String
  phonenumber_gte?: String
  phonenumber_contains?: String
  phonenumber_not_contains?: String
  phonenumber_starts_with?: String
  phonenumber_not_starts_with?: String
  phonenumber_ends_with?: String
  phonenumber_not_ends_with?: String
  photoURL?: String
  photoURL_not?: String
  photoURL_in?: String[] | String
  photoURL_not_in?: String[] | String
  photoURL_lt?: String
  photoURL_lte?: String
  photoURL_gt?: String
  photoURL_gte?: String
  photoURL_contains?: String
  photoURL_not_contains?: String
  photoURL_starts_with?: String
  photoURL_not_starts_with?: String
  photoURL_ends_with?: String
  photoURL_not_ends_with?: String
  place?: String
  place_not?: String
  place_in?: String[] | String
  place_not_in?: String[] | String
  place_lt?: String
  place_lte?: String
  place_gt?: String
  place_gte?: String
  place_contains?: String
  place_not_contains?: String
  place_starts_with?: String
  place_not_starts_with?: String
  place_ends_with?: String
  place_not_ends_with?: String
  price?: Float
  price_not?: Float
  price_in?: Float[] | Float
  price_not_in?: Float[] | Float
  price_lt?: Float
  price_lte?: Float
  price_gt?: Float
  price_gte?: Float
  rating?: Int
  rating_not?: Int
  rating_in?: Int[] | Int
  rating_not_in?: Int[] | Int
  rating_lt?: Int
  rating_lte?: Int
  rating_gt?: Int
  rating_gte?: Int
  ratingCount?: Int
  ratingCount_not?: Int
  ratingCount_in?: Int[] | Int
  ratingCount_not_in?: Int[] | Int
  ratingCount_lt?: Int
  ratingCount_lte?: Int
  ratingCount_gt?: Int
  ratingCount_gte?: Int
  reviews_every?: ReviewWhereInput
  reviews_some?: ReviewWhereInput
  reviews_none?: ReviewWhereInput
  tagline?: String
  tagline_not?: String
  tagline_in?: String[] | String
  tagline_not_in?: String[] | String
  tagline_lt?: String
  tagline_lte?: String
  tagline_gt?: String
  tagline_gte?: String
  tagline_contains?: String
  tagline_not_contains?: String
  tagline_starts_with?: String
  tagline_not_starts_with?: String
  tagline_ends_with?: String
  tagline_not_ends_with?: String
  title?: String
  title_not?: String
  title_in?: String[] | String
  title_not_in?: String[] | String
  title_lt?: String
  title_lte?: String
  title_gt?: String
  title_gte?: String
  title_contains?: String
  title_not_contains?: String
  title_starts_with?: String
  title_not_starts_with?: String
  title_ends_with?: String
  title_not_ends_with?: String
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  url?: String
  url_not?: String
  url_in?: String[] | String
  url_not_in?: String[] | String
  url_lt?: String
  url_lte?: String
  url_gt?: String
  url_gte?: String
  url_contains?: String
  url_not_contains?: String
  url_starts_with?: String
  url_not_starts_with?: String
  url_ends_with?: String
  url_not_ends_with?: String
  viewCount?: Int
  viewCount_not?: Int
  viewCount_in?: Int[] | Int
  viewCount_not_in?: Int[] | Int
  viewCount_lt?: Int
  viewCount_lte?: Int
  viewCount_gt?: Int
  viewCount_gte?: Int
  yomigana?: String
  yomigana_not?: String
  yomigana_in?: String[] | String
  yomigana_not_in?: String[] | String
  yomigana_lt?: String
  yomigana_lte?: String
  yomigana_gt?: String
  yomigana_gte?: String
  yomigana_contains?: String
  yomigana_not_contains?: String
  yomigana_starts_with?: String
  yomigana_not_starts_with?: String
  yomigana_ends_with?: String
  yomigana_not_ends_with?: String
  AND?: ServiceWhereInput[] | ServiceWhereInput
  OR?: ServiceWhereInput[] | ServiceWhereInput
  NOT?: ServiceWhereInput[] | ServiceWhereInput
}

export interface CategoryCreateInput {
  name: String
  services?: ServiceCreateManyWithoutCategoryInput
  shortDescription: String
  description: String
}

export interface CategorySubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType
  updatedFields_contains?: String
  updatedFields_contains_every?: String[] | String
  updatedFields_contains_some?: String[] | String
  node?: CategoryWhereInput
  AND?: CategorySubscriptionWhereInput[] | CategorySubscriptionWhereInput
  OR?: CategorySubscriptionWhereInput[] | CategorySubscriptionWhereInput
  NOT?: CategorySubscriptionWhereInput[] | CategorySubscriptionWhereInput
}

export interface ServiceCreateManyWithoutCategoryInput {
  create?:
    | ServiceCreateWithoutCategoryInput[]
    | ServiceCreateWithoutCategoryInput
  connect?: ServiceWhereUniqueInput[] | ServiceWhereUniqueInput
}

export interface ServiceUpdateInput {
  address?: String
  category?: CategoryUpdateOneWithoutServicesInput
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  reviews?: ReviewUpdateManyWithoutServiceInput
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface ServiceCreateWithoutCategoryInput {
  address?: String
  description: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  reviews?: ReviewCreateManyWithoutServiceInput
  tagline?: String
  title: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface ReviewUpdateManyMutationInput {
  rate?: Int
  rating?: Int
  text?: String
  serviceId?: String
  ownerId?: String
}

export interface ReviewCreateManyWithoutServiceInput {
  create?: ReviewCreateWithoutServiceInput[] | ReviewCreateWithoutServiceInput
  connect?: ReviewWhereUniqueInput[] | ReviewWhereUniqueInput
}

export interface ServiceUpsertWithoutReviewsInput {
  update: ServiceUpdateWithoutReviewsDataInput
  create: ServiceCreateWithoutReviewsInput
}

export interface ReviewCreateWithoutServiceInput {
  rate?: Int
  rating: Int
  text: String
  serviceId: String
  ownerId?: String
}

export interface ServiceUpdateOneRequiredWithoutReviewsInput {
  create?: ServiceCreateWithoutReviewsInput
  update?: ServiceUpdateWithoutReviewsDataInput
  upsert?: ServiceUpsertWithoutReviewsInput
  connect?: ServiceWhereUniqueInput
}

export interface CategoryUpdateInput {
  name?: String
  services?: ServiceUpdateManyWithoutCategoryInput
  shortDescription?: String
  description?: String
}

export type LinkWhereUniqueInput = AtLeastOne<{
  id: ID_Input
  url?: String
}>

export interface ServiceUpdateManyWithoutCategoryInput {
  create?:
    | ServiceCreateWithoutCategoryInput[]
    | ServiceCreateWithoutCategoryInput
  delete?: ServiceWhereUniqueInput[] | ServiceWhereUniqueInput
  connect?: ServiceWhereUniqueInput[] | ServiceWhereUniqueInput
  set?: ServiceWhereUniqueInput[] | ServiceWhereUniqueInput
  disconnect?: ServiceWhereUniqueInput[] | ServiceWhereUniqueInput
  update?:
    | ServiceUpdateWithWhereUniqueWithoutCategoryInput[]
    | ServiceUpdateWithWhereUniqueWithoutCategoryInput
  upsert?:
    | ServiceUpsertWithWhereUniqueWithoutCategoryInput[]
    | ServiceUpsertWithWhereUniqueWithoutCategoryInput
  deleteMany?: ServiceScalarWhereInput[] | ServiceScalarWhereInput
  updateMany?:
    | ServiceUpdateManyWithWhereNestedInput[]
    | ServiceUpdateManyWithWhereNestedInput
}

export interface LinkWhereInput {
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  author?: String
  author_not?: String
  author_in?: String[] | String
  author_not_in?: String[] | String
  author_lt?: String
  author_lte?: String
  author_gt?: String
  author_gte?: String
  author_contains?: String
  author_not_contains?: String
  author_starts_with?: String
  author_not_starts_with?: String
  author_ends_with?: String
  author_not_ends_with?: String
  content?: String
  content_not?: String
  content_in?: String[] | String
  content_not_in?: String[] | String
  content_lt?: String
  content_lte?: String
  content_gt?: String
  content_gte?: String
  content_contains?: String
  content_not_contains?: String
  content_starts_with?: String
  content_not_starts_with?: String
  content_ends_with?: String
  content_not_ends_with?: String
  description?: String
  description_not?: String
  description_in?: String[] | String
  description_not_in?: String[] | String
  description_lt?: String
  description_lte?: String
  description_gt?: String
  description_gte?: String
  description_contains?: String
  description_not_contains?: String
  description_starts_with?: String
  description_not_starts_with?: String
  description_ends_with?: String
  description_not_ends_with?: String
  publishedAt?: DateTimeInput
  publishedAt_not?: DateTimeInput
  publishedAt_in?: DateTimeInput[] | DateTimeInput
  publishedAt_not_in?: DateTimeInput[] | DateTimeInput
  publishedAt_lt?: DateTimeInput
  publishedAt_lte?: DateTimeInput
  publishedAt_gt?: DateTimeInput
  publishedAt_gte?: DateTimeInput
  sourceId?: String
  sourceId_not?: String
  sourceId_in?: String[] | String
  sourceId_not_in?: String[] | String
  sourceId_lt?: String
  sourceId_lte?: String
  sourceId_gt?: String
  sourceId_gte?: String
  sourceId_contains?: String
  sourceId_not_contains?: String
  sourceId_starts_with?: String
  sourceId_not_starts_with?: String
  sourceId_ends_with?: String
  sourceId_not_ends_with?: String
  sourceName?: String
  sourceName_not?: String
  sourceName_in?: String[] | String
  sourceName_not_in?: String[] | String
  sourceName_lt?: String
  sourceName_lte?: String
  sourceName_gt?: String
  sourceName_gte?: String
  sourceName_contains?: String
  sourceName_not_contains?: String
  sourceName_starts_with?: String
  sourceName_not_starts_with?: String
  sourceName_ends_with?: String
  sourceName_not_ends_with?: String
  title?: String
  title_not?: String
  title_in?: String[] | String
  title_not_in?: String[] | String
  title_lt?: String
  title_lte?: String
  title_gt?: String
  title_gte?: String
  title_contains?: String
  title_not_contains?: String
  title_starts_with?: String
  title_not_starts_with?: String
  title_ends_with?: String
  title_not_ends_with?: String
  url?: String
  url_not?: String
  url_in?: String[] | String
  url_not_in?: String[] | String
  url_lt?: String
  url_lte?: String
  url_gt?: String
  url_gte?: String
  url_contains?: String
  url_not_contains?: String
  url_starts_with?: String
  url_not_starts_with?: String
  url_ends_with?: String
  url_not_ends_with?: String
  AND?: LinkWhereInput[] | LinkWhereInput
  OR?: LinkWhereInput[] | LinkWhereInput
  NOT?: LinkWhereInput[] | LinkWhereInput
}

export interface ServiceUpdateWithWhereUniqueWithoutCategoryInput {
  where: ServiceWhereUniqueInput
  data: ServiceUpdateWithoutCategoryDataInput
}

export interface ReviewCreateInput {
  rate?: Int
  rating: Int
  text: String
  serviceId: String
  service: ServiceCreateOneWithoutReviewsInput
  ownerId?: String
}

export interface ServiceUpdateWithoutCategoryDataInput {
  address?: String
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  reviews?: ReviewUpdateManyWithoutServiceInput
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface LinkUpdateInput {
  author?: String
  content?: String
  description?: String
  publishedAt?: DateTimeInput
  sourceId?: String
  sourceName?: String
  title?: String
  url?: String
}

export interface ReviewUpdateManyWithoutServiceInput {
  create?: ReviewCreateWithoutServiceInput[] | ReviewCreateWithoutServiceInput
  delete?: ReviewWhereUniqueInput[] | ReviewWhereUniqueInput
  connect?: ReviewWhereUniqueInput[] | ReviewWhereUniqueInput
  set?: ReviewWhereUniqueInput[] | ReviewWhereUniqueInput
  disconnect?: ReviewWhereUniqueInput[] | ReviewWhereUniqueInput
  update?:
    | ReviewUpdateWithWhereUniqueWithoutServiceInput[]
    | ReviewUpdateWithWhereUniqueWithoutServiceInput
  upsert?:
    | ReviewUpsertWithWhereUniqueWithoutServiceInput[]
    | ReviewUpsertWithWhereUniqueWithoutServiceInput
  deleteMany?: ReviewScalarWhereInput[] | ReviewScalarWhereInput
  updateMany?:
    | ReviewUpdateManyWithWhereNestedInput[]
    | ReviewUpdateManyWithWhereNestedInput
}

export interface LinkCreateInput {
  author?: String
  content?: String
  description?: String
  publishedAt: DateTimeInput
  sourceId?: String
  sourceName?: String
  title: String
  url: String
}

export interface ReviewUpdateWithWhereUniqueWithoutServiceInput {
  where: ReviewWhereUniqueInput
  data: ReviewUpdateWithoutServiceDataInput
}

export interface ServiceUpsertNestedInput {
  update: ServiceUpdateDataInput
  create: ServiceCreateInput
}

export interface ServiceUpdateDataInput {
  address?: String
  category?: CategoryUpdateOneWithoutServicesInput
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  reviews?: ReviewUpdateManyWithoutServiceInput
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface ReviewWhereInput {
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  rate?: Int
  rate_not?: Int
  rate_in?: Int[] | Int
  rate_not_in?: Int[] | Int
  rate_lt?: Int
  rate_lte?: Int
  rate_gt?: Int
  rate_gte?: Int
  rating?: Int
  rating_not?: Int
  rating_in?: Int[] | Int
  rating_not_in?: Int[] | Int
  rating_lt?: Int
  rating_lte?: Int
  rating_gt?: Int
  rating_gte?: Int
  text?: String
  text_not?: String
  text_in?: String[] | String
  text_not_in?: String[] | String
  text_lt?: String
  text_lte?: String
  text_gt?: String
  text_gte?: String
  text_contains?: String
  text_not_contains?: String
  text_starts_with?: String
  text_not_starts_with?: String
  text_ends_with?: String
  text_not_ends_with?: String
  serviceId?: String
  serviceId_not?: String
  serviceId_in?: String[] | String
  serviceId_not_in?: String[] | String
  serviceId_lt?: String
  serviceId_lte?: String
  serviceId_gt?: String
  serviceId_gte?: String
  serviceId_contains?: String
  serviceId_not_contains?: String
  serviceId_starts_with?: String
  serviceId_not_starts_with?: String
  serviceId_ends_with?: String
  serviceId_not_ends_with?: String
  service?: ServiceWhereInput
  ownerId?: String
  ownerId_not?: String
  ownerId_in?: String[] | String
  ownerId_not_in?: String[] | String
  ownerId_lt?: String
  ownerId_lte?: String
  ownerId_gt?: String
  ownerId_gte?: String
  ownerId_contains?: String
  ownerId_not_contains?: String
  ownerId_starts_with?: String
  ownerId_not_starts_with?: String
  ownerId_ends_with?: String
  ownerId_not_ends_with?: String
  AND?: ReviewWhereInput[] | ReviewWhereInput
  OR?: ReviewWhereInput[] | ReviewWhereInput
  NOT?: ReviewWhereInput[] | ReviewWhereInput
}

export interface ReviewUpsertWithWhereUniqueWithoutServiceInput {
  where: ReviewWhereUniqueInput
  update: ReviewUpdateWithoutServiceDataInput
  create: ReviewCreateWithoutServiceInput
}

export interface LinkSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType
  updatedFields_contains?: String
  updatedFields_contains_every?: String[] | String
  updatedFields_contains_some?: String[] | String
  node?: LinkWhereInput
  AND?: LinkSubscriptionWhereInput[] | LinkSubscriptionWhereInput
  OR?: LinkSubscriptionWhereInput[] | LinkSubscriptionWhereInput
  NOT?: LinkSubscriptionWhereInput[] | LinkSubscriptionWhereInput
}

export interface ReviewScalarWhereInput {
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  rate?: Int
  rate_not?: Int
  rate_in?: Int[] | Int
  rate_not_in?: Int[] | Int
  rate_lt?: Int
  rate_lte?: Int
  rate_gt?: Int
  rate_gte?: Int
  rating?: Int
  rating_not?: Int
  rating_in?: Int[] | Int
  rating_not_in?: Int[] | Int
  rating_lt?: Int
  rating_lte?: Int
  rating_gt?: Int
  rating_gte?: Int
  text?: String
  text_not?: String
  text_in?: String[] | String
  text_not_in?: String[] | String
  text_lt?: String
  text_lte?: String
  text_gt?: String
  text_gte?: String
  text_contains?: String
  text_not_contains?: String
  text_starts_with?: String
  text_not_starts_with?: String
  text_ends_with?: String
  text_not_ends_with?: String
  serviceId?: String
  serviceId_not?: String
  serviceId_in?: String[] | String
  serviceId_not_in?: String[] | String
  serviceId_lt?: String
  serviceId_lte?: String
  serviceId_gt?: String
  serviceId_gte?: String
  serviceId_contains?: String
  serviceId_not_contains?: String
  serviceId_starts_with?: String
  serviceId_not_starts_with?: String
  serviceId_ends_with?: String
  serviceId_not_ends_with?: String
  ownerId?: String
  ownerId_not?: String
  ownerId_in?: String[] | String
  ownerId_not_in?: String[] | String
  ownerId_lt?: String
  ownerId_lte?: String
  ownerId_gt?: String
  ownerId_gte?: String
  ownerId_contains?: String
  ownerId_not_contains?: String
  ownerId_starts_with?: String
  ownerId_not_starts_with?: String
  ownerId_ends_with?: String
  ownerId_not_ends_with?: String
  AND?: ReviewScalarWhereInput[] | ReviewScalarWhereInput
  OR?: ReviewScalarWhereInput[] | ReviewScalarWhereInput
  NOT?: ReviewScalarWhereInput[] | ReviewScalarWhereInput
}

export interface ServiceUpdateManyMutationInput {
  address?: String
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface ReviewUpdateManyWithWhereNestedInput {
  where: ReviewScalarWhereInput
  data: ReviewUpdateManyDataInput
}

export interface CommentWhereInput {
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  text?: String
  text_not?: String
  text_in?: String[] | String
  text_not_in?: String[] | String
  text_lt?: String
  text_lte?: String
  text_gt?: String
  text_gte?: String
  text_contains?: String
  text_not_contains?: String
  text_starts_with?: String
  text_not_starts_with?: String
  text_ends_with?: String
  text_not_ends_with?: String
  service?: ServiceWhereInput
  ownerId?: String
  ownerId_not?: String
  ownerId_in?: String[] | String
  ownerId_not_in?: String[] | String
  ownerId_lt?: String
  ownerId_lte?: String
  ownerId_gt?: String
  ownerId_gte?: String
  ownerId_contains?: String
  ownerId_not_contains?: String
  ownerId_starts_with?: String
  ownerId_not_starts_with?: String
  ownerId_ends_with?: String
  ownerId_not_ends_with?: String
  AND?: CommentWhereInput[] | CommentWhereInput
  OR?: CommentWhereInput[] | CommentWhereInput
  NOT?: CommentWhereInput[] | CommentWhereInput
}

export interface ServiceUpdateOneRequiredInput {
  create?: ServiceCreateInput
  update?: ServiceUpdateDataInput
  upsert?: ServiceUpsertNestedInput
  connect?: ServiceWhereUniqueInput
}

export interface ReviewUpdateInput {
  rate?: Int
  rating?: Int
  text?: String
  serviceId?: String
  service?: ServiceUpdateOneRequiredWithoutReviewsInput
  ownerId?: String
}

export interface ServiceUpsertWithWhereUniqueWithoutCategoryInput {
  where: ServiceWhereUniqueInput
  update: ServiceUpdateWithoutCategoryDataInput
  create: ServiceCreateWithoutCategoryInput
}

export interface ServiceCreateOneWithoutReviewsInput {
  create?: ServiceCreateWithoutReviewsInput
  connect?: ServiceWhereUniqueInput
}

export interface ServiceScalarWhereInput {
  address?: String
  address_not?: String
  address_in?: String[] | String
  address_not_in?: String[] | String
  address_lt?: String
  address_lte?: String
  address_gt?: String
  address_gte?: String
  address_contains?: String
  address_not_contains?: String
  address_starts_with?: String
  address_not_starts_with?: String
  address_ends_with?: String
  address_not_ends_with?: String
  createdAt?: DateTimeInput
  createdAt_not?: DateTimeInput
  createdAt_in?: DateTimeInput[] | DateTimeInput
  createdAt_not_in?: DateTimeInput[] | DateTimeInput
  createdAt_lt?: DateTimeInput
  createdAt_lte?: DateTimeInput
  createdAt_gt?: DateTimeInput
  createdAt_gte?: DateTimeInput
  description?: String
  description_not?: String
  description_in?: String[] | String
  description_not_in?: String[] | String
  description_lt?: String
  description_lte?: String
  description_gt?: String
  description_gte?: String
  description_contains?: String
  description_not_contains?: String
  description_starts_with?: String
  description_not_starts_with?: String
  description_ends_with?: String
  description_not_ends_with?: String
  freetrial?: String
  freetrial_not?: String
  freetrial_in?: String[] | String
  freetrial_not_in?: String[] | String
  freetrial_lt?: String
  freetrial_lte?: String
  freetrial_gt?: String
  freetrial_gte?: String
  freetrial_contains?: String
  freetrial_not_contains?: String
  freetrial_starts_with?: String
  freetrial_not_starts_with?: String
  freetrial_ends_with?: String
  freetrial_not_ends_with?: String
  id?: ID_Input
  id_not?: ID_Input
  id_in?: ID_Input[] | ID_Input
  id_not_in?: ID_Input[] | ID_Input
  id_lt?: ID_Input
  id_lte?: ID_Input
  id_gt?: ID_Input
  id_gte?: ID_Input
  id_contains?: ID_Input
  id_not_contains?: ID_Input
  id_starts_with?: ID_Input
  id_not_starts_with?: ID_Input
  id_ends_with?: ID_Input
  id_not_ends_with?: ID_Input
  isOnline?: Boolean
  isOnline_not?: Boolean
  inquiry?: String
  inquiry_not?: String
  inquiry_in?: String[] | String
  inquiry_not_in?: String[] | String
  inquiry_lt?: String
  inquiry_lte?: String
  inquiry_gt?: String
  inquiry_gte?: String
  inquiry_contains?: String
  inquiry_not_contains?: String
  inquiry_starts_with?: String
  inquiry_not_starts_with?: String
  inquiry_ends_with?: String
  inquiry_not_ends_with?: String
  likeCount?: Int
  likeCount_not?: Int
  likeCount_in?: Int[] | Int
  likeCount_not_in?: Int[] | Int
  likeCount_lt?: Int
  likeCount_lte?: Int
  likeCount_gt?: Int
  likeCount_gte?: Int
  multiplans?: String
  multiplans_not?: String
  multiplans_in?: String[] | String
  multiplans_not_in?: String[] | String
  multiplans_lt?: String
  multiplans_lte?: String
  multiplans_gt?: String
  multiplans_gte?: String
  multiplans_contains?: String
  multiplans_not_contains?: String
  multiplans_starts_with?: String
  multiplans_not_starts_with?: String
  multiplans_ends_with?: String
  multiplans_not_ends_with?: String
  note?: String
  note_not?: String
  note_in?: String[] | String
  note_not_in?: String[] | String
  note_lt?: String
  note_lte?: String
  note_gt?: String
  note_gte?: String
  note_contains?: String
  note_not_contains?: String
  note_starts_with?: String
  note_not_starts_with?: String
  note_ends_with?: String
  note_not_ends_with?: String
  phonenumber?: String
  phonenumber_not?: String
  phonenumber_in?: String[] | String
  phonenumber_not_in?: String[] | String
  phonenumber_lt?: String
  phonenumber_lte?: String
  phonenumber_gt?: String
  phonenumber_gte?: String
  phonenumber_contains?: String
  phonenumber_not_contains?: String
  phonenumber_starts_with?: String
  phonenumber_not_starts_with?: String
  phonenumber_ends_with?: String
  phonenumber_not_ends_with?: String
  photoURL?: String
  photoURL_not?: String
  photoURL_in?: String[] | String
  photoURL_not_in?: String[] | String
  photoURL_lt?: String
  photoURL_lte?: String
  photoURL_gt?: String
  photoURL_gte?: String
  photoURL_contains?: String
  photoURL_not_contains?: String
  photoURL_starts_with?: String
  photoURL_not_starts_with?: String
  photoURL_ends_with?: String
  photoURL_not_ends_with?: String
  place?: String
  place_not?: String
  place_in?: String[] | String
  place_not_in?: String[] | String
  place_lt?: String
  place_lte?: String
  place_gt?: String
  place_gte?: String
  place_contains?: String
  place_not_contains?: String
  place_starts_with?: String
  place_not_starts_with?: String
  place_ends_with?: String
  place_not_ends_with?: String
  price?: Float
  price_not?: Float
  price_in?: Float[] | Float
  price_not_in?: Float[] | Float
  price_lt?: Float
  price_lte?: Float
  price_gt?: Float
  price_gte?: Float
  rating?: Int
  rating_not?: Int
  rating_in?: Int[] | Int
  rating_not_in?: Int[] | Int
  rating_lt?: Int
  rating_lte?: Int
  rating_gt?: Int
  rating_gte?: Int
  ratingCount?: Int
  ratingCount_not?: Int
  ratingCount_in?: Int[] | Int
  ratingCount_not_in?: Int[] | Int
  ratingCount_lt?: Int
  ratingCount_lte?: Int
  ratingCount_gt?: Int
  ratingCount_gte?: Int
  tagline?: String
  tagline_not?: String
  tagline_in?: String[] | String
  tagline_not_in?: String[] | String
  tagline_lt?: String
  tagline_lte?: String
  tagline_gt?: String
  tagline_gte?: String
  tagline_contains?: String
  tagline_not_contains?: String
  tagline_starts_with?: String
  tagline_not_starts_with?: String
  tagline_ends_with?: String
  tagline_not_ends_with?: String
  title?: String
  title_not?: String
  title_in?: String[] | String
  title_not_in?: String[] | String
  title_lt?: String
  title_lte?: String
  title_gt?: String
  title_gte?: String
  title_contains?: String
  title_not_contains?: String
  title_starts_with?: String
  title_not_starts_with?: String
  title_ends_with?: String
  title_not_ends_with?: String
  updatedAt?: DateTimeInput
  updatedAt_not?: DateTimeInput
  updatedAt_in?: DateTimeInput[] | DateTimeInput
  updatedAt_not_in?: DateTimeInput[] | DateTimeInput
  updatedAt_lt?: DateTimeInput
  updatedAt_lte?: DateTimeInput
  updatedAt_gt?: DateTimeInput
  updatedAt_gte?: DateTimeInput
  url?: String
  url_not?: String
  url_in?: String[] | String
  url_not_in?: String[] | String
  url_lt?: String
  url_lte?: String
  url_gt?: String
  url_gte?: String
  url_contains?: String
  url_not_contains?: String
  url_starts_with?: String
  url_not_starts_with?: String
  url_ends_with?: String
  url_not_ends_with?: String
  viewCount?: Int
  viewCount_not?: Int
  viewCount_in?: Int[] | Int
  viewCount_not_in?: Int[] | Int
  viewCount_lt?: Int
  viewCount_lte?: Int
  viewCount_gt?: Int
  viewCount_gte?: Int
  yomigana?: String
  yomigana_not?: String
  yomigana_in?: String[] | String
  yomigana_not_in?: String[] | String
  yomigana_lt?: String
  yomigana_lte?: String
  yomigana_gt?: String
  yomigana_gte?: String
  yomigana_contains?: String
  yomigana_not_contains?: String
  yomigana_starts_with?: String
  yomigana_not_starts_with?: String
  yomigana_ends_with?: String
  yomigana_not_ends_with?: String
  AND?: ServiceScalarWhereInput[] | ServiceScalarWhereInput
  OR?: ServiceScalarWhereInput[] | ServiceScalarWhereInput
  NOT?: ServiceScalarWhereInput[] | ServiceScalarWhereInput
}

export type ReviewWhereUniqueInput = AtLeastOne<{
  id: ID_Input
}>

export interface ServiceUpdateManyWithWhereNestedInput {
  where: ServiceScalarWhereInput
  data: ServiceUpdateManyDataInput
}

export type ServiceWhereUniqueInput = AtLeastOne<{
  id: ID_Input
}>

export interface ServiceUpdateManyDataInput {
  address?: String
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface CommentSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType
  updatedFields_contains?: String
  updatedFields_contains_every?: String[] | String
  updatedFields_contains_some?: String[] | String
  node?: CommentWhereInput
  AND?: CommentSubscriptionWhereInput[] | CommentSubscriptionWhereInput
  OR?: CommentSubscriptionWhereInput[] | CommentSubscriptionWhereInput
  NOT?: CommentSubscriptionWhereInput[] | CommentSubscriptionWhereInput
}

export interface CategoryUpdateManyMutationInput {
  name?: String
  shortDescription?: String
  description?: String
}

export interface ServiceUpdateWithoutReviewsDataInput {
  address?: String
  category?: CategoryUpdateOneWithoutServicesInput
  description?: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title?: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface CommentUpdateInput {
  text?: String
  service?: ServiceUpdateOneRequiredInput
  ownerId?: String
}

export interface LinkUpdateManyMutationInput {
  author?: String
  content?: String
  description?: String
  publishedAt?: DateTimeInput
  sourceId?: String
  sourceName?: String
  title?: String
  url?: String
}

export interface ServiceCreateInput {
  address?: String
  category?: CategoryCreateOneWithoutServicesInput
  description: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  reviews?: ReviewCreateManyWithoutServiceInput
  tagline?: String
  title: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export interface ServiceCreateOneInput {
  create?: ServiceCreateInput
  connect?: ServiceWhereUniqueInput
}

export interface CommentCreateInput {
  text: String
  service: ServiceCreateOneInput
  ownerId?: String
}

export interface CategoryCreateWithoutServicesInput {
  name: String
  shortDescription: String
  description: String
}

export interface CommentUpdateManyMutationInput {
  text?: String
  ownerId?: String
}

export interface ServiceCreateWithoutReviewsInput {
  address?: String
  category?: CategoryCreateOneWithoutServicesInput
  description: String
  freetrial?: String
  isOnline?: Boolean
  inquiry?: String
  likeCount?: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title: String
  url?: String
  viewCount?: Int
  yomigana?: String
}

export type CommentWhereUniqueInput = AtLeastOne<{
  id: ID_Input
}>

export interface ReviewSubscriptionWhereInput {
  mutation_in?: MutationType[] | MutationType
  updatedFields_contains?: String
  updatedFields_contains_every?: String[] | String
  updatedFields_contains_some?: String[] | String
  node?: ReviewWhereInput
  AND?: ReviewSubscriptionWhereInput[] | ReviewSubscriptionWhereInput
  OR?: ReviewSubscriptionWhereInput[] | ReviewSubscriptionWhereInput
  NOT?: ReviewSubscriptionWhereInput[] | ReviewSubscriptionWhereInput
}

export interface NodeNode {
  id: ID_Output
}

export interface ServicePreviousValues {
  address?: String
  createdAt: DateTimeOutput
  description: String
  freetrial?: String
  id: ID_Output
  isOnline?: Boolean
  inquiry?: String
  likeCount: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title: String
  updatedAt: DateTimeOutput
  url?: String
  viewCount: Int
  yomigana?: String
}

export interface ServicePreviousValuesPromise
  extends Promise<ServicePreviousValues>,
    Fragmentable {
  address: () => Promise<String>
  createdAt: () => Promise<DateTimeOutput>
  description: () => Promise<String>
  freetrial: () => Promise<String>
  id: () => Promise<ID_Output>
  isOnline: () => Promise<Boolean>
  inquiry: () => Promise<String>
  likeCount: () => Promise<Int>
  multiplans: () => Promise<String>
  note: () => Promise<String>
  phonenumber: () => Promise<String>
  photoURL: () => Promise<String>
  place: () => Promise<String>
  price: () => Promise<Float>
  rating: () => Promise<Int>
  ratingCount: () => Promise<Int>
  tagline: () => Promise<String>
  title: () => Promise<String>
  updatedAt: () => Promise<DateTimeOutput>
  url: () => Promise<String>
  viewCount: () => Promise<Int>
  yomigana: () => Promise<String>
}

export interface ServicePreviousValuesSubscription
  extends Promise<AsyncIterator<ServicePreviousValues>>,
    Fragmentable {
  address: () => Promise<AsyncIterator<String>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  description: () => Promise<AsyncIterator<String>>
  freetrial: () => Promise<AsyncIterator<String>>
  id: () => Promise<AsyncIterator<ID_Output>>
  isOnline: () => Promise<AsyncIterator<Boolean>>
  inquiry: () => Promise<AsyncIterator<String>>
  likeCount: () => Promise<AsyncIterator<Int>>
  multiplans: () => Promise<AsyncIterator<String>>
  note: () => Promise<AsyncIterator<String>>
  phonenumber: () => Promise<AsyncIterator<String>>
  photoURL: () => Promise<AsyncIterator<String>>
  place: () => Promise<AsyncIterator<String>>
  price: () => Promise<AsyncIterator<Float>>
  rating: () => Promise<AsyncIterator<Int>>
  ratingCount: () => Promise<AsyncIterator<Int>>
  tagline: () => Promise<AsyncIterator<String>>
  title: () => Promise<AsyncIterator<String>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  url: () => Promise<AsyncIterator<String>>
  viewCount: () => Promise<AsyncIterator<Int>>
  yomigana: () => Promise<AsyncIterator<String>>
}

export interface CommentEdge {
  node: Comment
  cursor: String
}

export interface CommentEdgePromise extends Promise<CommentEdge>, Fragmentable {
  node: <T = CommentPromise>() => T
  cursor: () => Promise<String>
}

export interface CommentEdgeSubscription
  extends Promise<AsyncIterator<CommentEdge>>,
    Fragmentable {
  node: <T = CommentSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface LinkPreviousValues {
  id: ID_Output
  author?: String
  content?: String
  description?: String
  publishedAt: DateTimeOutput
  sourceId?: String
  sourceName?: String
  title: String
  url: String
}

export interface LinkPreviousValuesPromise
  extends Promise<LinkPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  author: () => Promise<String>
  content: () => Promise<String>
  description: () => Promise<String>
  publishedAt: () => Promise<DateTimeOutput>
  sourceId: () => Promise<String>
  sourceName: () => Promise<String>
  title: () => Promise<String>
  url: () => Promise<String>
}

export interface LinkPreviousValuesSubscription
  extends Promise<AsyncIterator<LinkPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  author: () => Promise<AsyncIterator<String>>
  content: () => Promise<AsyncIterator<String>>
  description: () => Promise<AsyncIterator<String>>
  publishedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  sourceId: () => Promise<AsyncIterator<String>>
  sourceName: () => Promise<AsyncIterator<String>>
  title: () => Promise<AsyncIterator<String>>
  url: () => Promise<AsyncIterator<String>>
}

export interface CommentConnection {
  pageInfo: PageInfo
  edges: CommentEdge[]
}

export interface CommentConnectionPromise
  extends Promise<CommentConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<CommentEdge>>() => T
  aggregate: <T = AggregateCommentPromise>() => T
}

export interface CommentConnectionSubscription
  extends Promise<AsyncIterator<CommentConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<CommentEdgeSubscription>>>() => T
  aggregate: <T = AggregateCommentSubscription>() => T
}

export interface Comment {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  text: String
  ownerId?: String
}

export interface CommentPromise extends Promise<Comment>, Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  text: () => Promise<String>
  service: <T = ServicePromise>() => T
  ownerId: () => Promise<String>
}

export interface CommentSubscription
  extends Promise<AsyncIterator<Comment>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  text: () => Promise<AsyncIterator<String>>
  service: <T = ServiceSubscription>() => T
  ownerId: () => Promise<AsyncIterator<String>>
}

export interface Service {
  address?: String
  createdAt: DateTimeOutput
  description: String
  freetrial?: String
  id: ID_Output
  isOnline?: Boolean
  inquiry?: String
  likeCount: Int
  multiplans?: String
  note?: String
  phonenumber?: String
  photoURL?: String
  place?: String
  price?: Float
  rating?: Int
  ratingCount?: Int
  tagline?: String
  title: String
  updatedAt: DateTimeOutput
  url?: String
  viewCount: Int
  yomigana?: String
}

export interface ServicePromise extends Promise<Service>, Fragmentable {
  address: () => Promise<String>
  category: <T = CategoryPromise>() => T
  createdAt: () => Promise<DateTimeOutput>
  description: () => Promise<String>
  freetrial: () => Promise<String>
  id: () => Promise<ID_Output>
  isOnline: () => Promise<Boolean>
  inquiry: () => Promise<String>
  likeCount: () => Promise<Int>
  multiplans: () => Promise<String>
  note: () => Promise<String>
  phonenumber: () => Promise<String>
  photoURL: () => Promise<String>
  place: () => Promise<String>
  price: () => Promise<Float>
  rating: () => Promise<Int>
  ratingCount: () => Promise<Int>
  reviews: <T = FragmentableArray<Review>>(args?: {
    where?: ReviewWhereInput
    orderBy?: ReviewOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
  tagline: () => Promise<String>
  title: () => Promise<String>
  updatedAt: () => Promise<DateTimeOutput>
  url: () => Promise<String>
  viewCount: () => Promise<Int>
  yomigana: () => Promise<String>
}

export interface ServiceSubscription
  extends Promise<AsyncIterator<Service>>,
    Fragmentable {
  address: () => Promise<AsyncIterator<String>>
  category: <T = CategorySubscription>() => T
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  description: () => Promise<AsyncIterator<String>>
  freetrial: () => Promise<AsyncIterator<String>>
  id: () => Promise<AsyncIterator<ID_Output>>
  isOnline: () => Promise<AsyncIterator<Boolean>>
  inquiry: () => Promise<AsyncIterator<String>>
  likeCount: () => Promise<AsyncIterator<Int>>
  multiplans: () => Promise<AsyncIterator<String>>
  note: () => Promise<AsyncIterator<String>>
  phonenumber: () => Promise<AsyncIterator<String>>
  photoURL: () => Promise<AsyncIterator<String>>
  place: () => Promise<AsyncIterator<String>>
  price: () => Promise<AsyncIterator<Float>>
  rating: () => Promise<AsyncIterator<Int>>
  ratingCount: () => Promise<AsyncIterator<Int>>
  reviews: <T = Promise<AsyncIterator<ReviewSubscription>>>(args?: {
    where?: ReviewWhereInput
    orderBy?: ReviewOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
  tagline: () => Promise<AsyncIterator<String>>
  title: () => Promise<AsyncIterator<String>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  url: () => Promise<AsyncIterator<String>>
  viewCount: () => Promise<AsyncIterator<Int>>
  yomigana: () => Promise<AsyncIterator<String>>
}

export interface ReviewPreviousValues {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  rate?: Int
  rating: Int
  text: String
  serviceId: String
  ownerId?: String
}

export interface ReviewPreviousValuesPromise
  extends Promise<ReviewPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  rate: () => Promise<Int>
  rating: () => Promise<Int>
  text: () => Promise<String>
  serviceId: () => Promise<String>
  ownerId: () => Promise<String>
}

export interface ReviewPreviousValuesSubscription
  extends Promise<AsyncIterator<ReviewPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  rate: () => Promise<AsyncIterator<Int>>
  rating: () => Promise<AsyncIterator<Int>>
  text: () => Promise<AsyncIterator<String>>
  serviceId: () => Promise<AsyncIterator<String>>
  ownerId: () => Promise<AsyncIterator<String>>
}

export interface BatchPayload {
  count: Long
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>
}

export interface ServiceEdge {
  node: Service
  cursor: String
}

export interface ServiceEdgePromise extends Promise<ServiceEdge>, Fragmentable {
  node: <T = ServicePromise>() => T
  cursor: () => Promise<String>
}

export interface ServiceEdgeSubscription
  extends Promise<AsyncIterator<ServiceEdge>>,
    Fragmentable {
  node: <T = ServiceSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface AggregateCategory {
  count: Int
}

export interface AggregateCategoryPromise
  extends Promise<AggregateCategory>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateCategorySubscription
  extends Promise<AsyncIterator<AggregateCategory>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface AggregateReview {
  count: Int
}

export interface AggregateReviewPromise
  extends Promise<AggregateReview>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateReviewSubscription
  extends Promise<AsyncIterator<AggregateReview>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface CategoryEdge {
  node: Category
  cursor: String
}

export interface CategoryEdgePromise
  extends Promise<CategoryEdge>,
    Fragmentable {
  node: <T = CategoryPromise>() => T
  cursor: () => Promise<String>
}

export interface CategoryEdgeSubscription
  extends Promise<AsyncIterator<CategoryEdge>>,
    Fragmentable {
  node: <T = CategorySubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface ReviewConnection {
  pageInfo: PageInfo
  edges: ReviewEdge[]
}

export interface ReviewConnectionPromise
  extends Promise<ReviewConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<ReviewEdge>>() => T
  aggregate: <T = AggregateReviewPromise>() => T
}

export interface ReviewConnectionSubscription
  extends Promise<AsyncIterator<ReviewConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<ReviewEdgeSubscription>>>() => T
  aggregate: <T = AggregateReviewSubscription>() => T
}

export interface PageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor?: String
  endCursor?: String
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>
  hasPreviousPage: () => Promise<Boolean>
  startCursor: () => Promise<String>
  endCursor: () => Promise<String>
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>
  startCursor: () => Promise<AsyncIterator<String>>
  endCursor: () => Promise<AsyncIterator<String>>
}

export interface LinkEdge {
  node: Link
  cursor: String
}

export interface LinkEdgePromise extends Promise<LinkEdge>, Fragmentable {
  node: <T = LinkPromise>() => T
  cursor: () => Promise<String>
}

export interface LinkEdgeSubscription
  extends Promise<AsyncIterator<LinkEdge>>,
    Fragmentable {
  node: <T = LinkSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface Category {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  name: String
  shortDescription: String
  description: String
}

export interface CategoryPromise extends Promise<Category>, Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  name: () => Promise<String>
  services: <T = FragmentableArray<Service>>(args?: {
    where?: ServiceWhereInput
    orderBy?: ServiceOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
  shortDescription: () => Promise<String>
  description: () => Promise<String>
}

export interface CategorySubscription
  extends Promise<AsyncIterator<Category>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  name: () => Promise<AsyncIterator<String>>
  services: <T = Promise<AsyncIterator<ServiceSubscription>>>(args?: {
    where?: ServiceWhereInput
    orderBy?: ServiceOrderByInput
    skip?: Int
    after?: String
    before?: String
    first?: Int
    last?: Int
  }) => T
  shortDescription: () => Promise<AsyncIterator<String>>
  description: () => Promise<AsyncIterator<String>>
}

export interface ReviewSubscriptionPayload {
  mutation: MutationType
  node: Review
  updatedFields: String[]
  previousValues: ReviewPreviousValues
}

export interface ReviewSubscriptionPayloadPromise
  extends Promise<ReviewSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = ReviewPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = ReviewPreviousValuesPromise>() => T
}

export interface ReviewSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<ReviewSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = ReviewSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = ReviewPreviousValuesSubscription>() => T
}

export interface CategorySubscriptionPayload {
  mutation: MutationType
  node: Category
  updatedFields: String[]
  previousValues: CategoryPreviousValues
}

export interface CategorySubscriptionPayloadPromise
  extends Promise<CategorySubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = CategoryPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = CategoryPreviousValuesPromise>() => T
}

export interface CategorySubscriptionPayloadSubscription
  extends Promise<AsyncIterator<CategorySubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = CategorySubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = CategoryPreviousValuesSubscription>() => T
}

export interface AggregateComment {
  count: Int
}

export interface AggregateCommentPromise
  extends Promise<AggregateComment>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateCommentSubscription
  extends Promise<AsyncIterator<AggregateComment>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface CategoryPreviousValues {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  name: String
  shortDescription: String
  description: String
}

export interface CategoryPreviousValuesPromise
  extends Promise<CategoryPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  name: () => Promise<String>
  shortDescription: () => Promise<String>
  description: () => Promise<String>
}

export interface CategoryPreviousValuesSubscription
  extends Promise<AsyncIterator<CategoryPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  name: () => Promise<AsyncIterator<String>>
  shortDescription: () => Promise<AsyncIterator<String>>
  description: () => Promise<AsyncIterator<String>>
}

export interface AggregateService {
  count: Int
}

export interface AggregateServicePromise
  extends Promise<AggregateService>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateServiceSubscription
  extends Promise<AsyncIterator<AggregateService>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface CategoryConnection {
  pageInfo: PageInfo
  edges: CategoryEdge[]
}

export interface CategoryConnectionPromise
  extends Promise<CategoryConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<CategoryEdge>>() => T
  aggregate: <T = AggregateCategoryPromise>() => T
}

export interface CategoryConnectionSubscription
  extends Promise<AsyncIterator<CategoryConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<CategoryEdgeSubscription>>>() => T
  aggregate: <T = AggregateCategorySubscription>() => T
}

export interface ReviewEdge {
  node: Review
  cursor: String
}

export interface ReviewEdgePromise extends Promise<ReviewEdge>, Fragmentable {
  node: <T = ReviewPromise>() => T
  cursor: () => Promise<String>
}

export interface ReviewEdgeSubscription
  extends Promise<AsyncIterator<ReviewEdge>>,
    Fragmentable {
  node: <T = ReviewSubscription>() => T
  cursor: () => Promise<AsyncIterator<String>>
}

export interface LinkConnection {
  pageInfo: PageInfo
  edges: LinkEdge[]
}

export interface LinkConnectionPromise
  extends Promise<LinkConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<LinkEdge>>() => T
  aggregate: <T = AggregateLinkPromise>() => T
}

export interface LinkConnectionSubscription
  extends Promise<AsyncIterator<LinkConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<LinkEdgeSubscription>>>() => T
  aggregate: <T = AggregateLinkSubscription>() => T
}

export interface LinkSubscriptionPayload {
  mutation: MutationType
  node: Link
  updatedFields: String[]
  previousValues: LinkPreviousValues
}

export interface LinkSubscriptionPayloadPromise
  extends Promise<LinkSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = LinkPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = LinkPreviousValuesPromise>() => T
}

export interface LinkSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<LinkSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = LinkSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = LinkPreviousValuesSubscription>() => T
}

export interface Review {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  rate?: Int
  rating: Int
  text: String
  serviceId: String
  ownerId?: String
}

export interface ReviewPromise extends Promise<Review>, Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  rate: () => Promise<Int>
  rating: () => Promise<Int>
  text: () => Promise<String>
  serviceId: () => Promise<String>
  service: <T = ServicePromise>() => T
  ownerId: () => Promise<String>
}

export interface ReviewSubscription
  extends Promise<AsyncIterator<Review>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  rate: () => Promise<AsyncIterator<Int>>
  rating: () => Promise<AsyncIterator<Int>>
  text: () => Promise<AsyncIterator<String>>
  serviceId: () => Promise<AsyncIterator<String>>
  service: <T = ServiceSubscription>() => T
  ownerId: () => Promise<AsyncIterator<String>>
}

export interface CommentPreviousValues {
  id: ID_Output
  createdAt: DateTimeOutput
  updatedAt: DateTimeOutput
  text: String
  ownerId?: String
}

export interface CommentPreviousValuesPromise
  extends Promise<CommentPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>
  createdAt: () => Promise<DateTimeOutput>
  updatedAt: () => Promise<DateTimeOutput>
  text: () => Promise<String>
  ownerId: () => Promise<String>
}

export interface CommentPreviousValuesSubscription
  extends Promise<AsyncIterator<CommentPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  createdAt: () => Promise<AsyncIterator<DateTimeOutput>>
  updatedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  text: () => Promise<AsyncIterator<String>>
  ownerId: () => Promise<AsyncIterator<String>>
}

export interface CommentSubscriptionPayload {
  mutation: MutationType
  node: Comment
  updatedFields: String[]
  previousValues: CommentPreviousValues
}

export interface CommentSubscriptionPayloadPromise
  extends Promise<CommentSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = CommentPromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = CommentPreviousValuesPromise>() => T
}

export interface CommentSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<CommentSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = CommentSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = CommentPreviousValuesSubscription>() => T
}

export interface Link {
  id: ID_Output
  author?: String
  content?: String
  description?: String
  publishedAt: DateTimeOutput
  sourceId?: String
  sourceName?: String
  title: String
  url: String
}

export interface LinkPromise extends Promise<Link>, Fragmentable {
  id: () => Promise<ID_Output>
  author: () => Promise<String>
  content: () => Promise<String>
  description: () => Promise<String>
  publishedAt: () => Promise<DateTimeOutput>
  sourceId: () => Promise<String>
  sourceName: () => Promise<String>
  title: () => Promise<String>
  url: () => Promise<String>
}

export interface LinkSubscription
  extends Promise<AsyncIterator<Link>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>
  author: () => Promise<AsyncIterator<String>>
  content: () => Promise<AsyncIterator<String>>
  description: () => Promise<AsyncIterator<String>>
  publishedAt: () => Promise<AsyncIterator<DateTimeOutput>>
  sourceId: () => Promise<AsyncIterator<String>>
  sourceName: () => Promise<AsyncIterator<String>>
  title: () => Promise<AsyncIterator<String>>
  url: () => Promise<AsyncIterator<String>>
}

export interface AggregateLink {
  count: Int
}

export interface AggregateLinkPromise
  extends Promise<AggregateLink>,
    Fragmentable {
  count: () => Promise<Int>
}

export interface AggregateLinkSubscription
  extends Promise<AsyncIterator<AggregateLink>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>
}

export interface ServiceConnection {
  pageInfo: PageInfo
  edges: ServiceEdge[]
}

export interface ServiceConnectionPromise
  extends Promise<ServiceConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T
  edges: <T = FragmentableArray<ServiceEdge>>() => T
  aggregate: <T = AggregateServicePromise>() => T
}

export interface ServiceConnectionSubscription
  extends Promise<AsyncIterator<ServiceConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T
  edges: <T = Promise<AsyncIterator<ServiceEdgeSubscription>>>() => T
  aggregate: <T = AggregateServiceSubscription>() => T
}

export interface ServiceSubscriptionPayload {
  mutation: MutationType
  node: Service
  updatedFields: String[]
  previousValues: ServicePreviousValues
}

export interface ServiceSubscriptionPayloadPromise
  extends Promise<ServiceSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>
  node: <T = ServicePromise>() => T
  updatedFields: () => Promise<String[]>
  previousValues: <T = ServicePreviousValuesPromise>() => T
}

export interface ServiceSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<ServiceSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>
  node: <T = ServiceSubscription>() => T
  updatedFields: () => Promise<AsyncIterator<String[]>>
  previousValues: <T = ServicePreviousValuesSubscription>() => T
}

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1. 
*/
export type Int = number

export type Long = string

/*
The `Float` scalar type represents signed double-precision fractional values as specified by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_floating_point). 
*/
export type Float = number

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number
export type ID_Output = string

/*
DateTime scalar input type, allowing Date
*/
export type DateTimeInput = Date | string

/*
DateTime scalar output type, which is always a string
*/
export type DateTimeOutput = string

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: 'Link',
    embedded: false
  },
  {
    name: 'Comment',
    embedded: false
  },
  {
    name: 'Review',
    embedded: false
  },
  {
    name: 'Category',
    embedded: false
  },
  {
    name: 'Service',
    embedded: false
  }
]

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `https://subsclog.now.sh/default/default`,
  secret: `${process.env['SECRET']}`
})
export const prisma = new Prisma()
